---
- hosts: all
  become: yes
  become_user: horza
  tasks: 
    
  - name: Check current user
    command: whoami
    register: output
    changed_when: False
  
  - name: Print current user
    debug: var=output.stdout

  - name: Ansible check Julia installed
    stat:
      path: /home/horza/julia-1.6.1
    register: julia

  - name: Download Julia
    shell: wget https://julialang-s3.julialang.org/bin/linux/x64/1.6/julia-1.6.1-linux-x86_64.tar.gz
    args:
      chdir: /home/horza
    when: julia.stat.exists == False

  - name: Install Julia
    shell: tar zxvf julia-1.6.1-linux-x86_64.tar.gz
    args:
      chdir: /home/horza
    when: julia.stat.exists == False

  - name: Install Julia (2)
    shell: echo export PATH="$PATH:/home/horza/julia-1.6.1/bin" >> .bashrc
    args:
      chdir: /home/horza
    when: julia.stat.exists == False

  - name: Install Rust
    shell: curl https://sh.rustup.rs -sSf | sh -s -- -y
    args:
      chdir: /home/horza
 
 